name: build-push-django-container

on:
    workflow_dispatch:
    push:
        branches: ["main"]

env:
    REGISTRY: docker.io
          
jobs:
    hello-container:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PASS }}

            - name: Build and Push the Docker image
            # docker-compose build --no-cache --force-rm 
              run: |
                docker build -t django-app-image .
                docker tag django-app-image:latest robin1711/my-test-repository:1.0.0
                docker tag django-app-image:latest robin1711/my-test-repository:latest


            - name: Build and Push the Docker image
              run: |
                docker push robin1711/my-test-repository:0.2.0
                docker push robin1711/my-test-repository:latest
    