name: dev-docker-build-django-tests

on:
    workflow_dispatch:
    pull_request:
        branches: ["test", "development"]


jobs:
  django-tests:
    runs-on: ubuntu-latest
    environment: development
    
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
    
    env:
      PYTHON_VERSION: 3.11
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test_db"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations and Run tests
        run: |
          python src/manage.py makemigrations
          python src/manage.py migrate
          python src/manage.py test app
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}  # Use the DATABASE_URL environment variable

  docker-build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t image:test -f deployment/production/Dockerfile .

