name: hello-world

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-helloworld:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull and Run hello-world image
        run: |
          docker pull hello-world
          docker run hello-world
