name: push-container

on:
    workflow_dispatch:
    push:
        branches: ["production"]

env:
    REGISTRY: docker.io
     
jobs:
    hello-container:
        runs-on: ubuntu-latest
        environment: production

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build and Push the Docker image
            run: |
              docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:beta -f deployment/production/Dockerfile .
              docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:beta
