name: run-docker-builds

on:
    workflow_dispatch:
    push:
        branches: ["test", "development"]

env:
    MY_ENV_VAR: value
     
jobs:
    docker-build:
        runs-on: ubuntu-latest
        environment: test

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Echo something as placeholder
              run: echo "This has not been implemented yet"
