name: run-django-tests

on:
    workflow_dispatch:
    pull_request:
        branches: ["main", "test"]

env:
    MY_ENV_VAR: value
     
jobs:
    django-tests:
        runs-on: ubuntu-latest
        environment: test

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          
          - name: Echo something as placeholder
            run: echo "something"
