name: test-docker-build-django-tests

on:
    workflow_dispatch:
    pull_request:
        branches: ["main"]

env:
    MY_ENV_VAR: value
     
jobs:
  django-tests:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Run tests
        run: |
          python src/manage.py makemigrations
          python src/manage.py migrate
          python src/manage.py test app

  docker-build:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t image:test -f deployment/production/Dockerfile .

